apiVersion: v1
kind: ServiceAccount
metadata:
  name: apply
  namespace: target
---
apiVersion: batch/v1
kind: Job
metadata:
  name: apply
  namespace: target
  labels:
    app: apply
spec:
  template:
    metadata:
      labels:
        app: apply
    spec:
      serviceAccountName: apply
      containers:
      - name: apply
        image: apply
      restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-services
  namespace: target
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services-binding
  namespace: target
subjects:
  - kind: ServiceAccount
    name: apply
    namespace: target
roleRef:
  kind: Role
  name: read-services
  apiGroup: rbac.authorization.k8s.io

