[project]
name = "cabinet"
version = "1.0.0"
requires-python = ">=3.12"

dependencies = ["poethepoet", "pytest-bdd"]

[tool.poe.tasks.dev]
cmd = "pytest -xsm 'dev and not skip' --tb=short tests/"

[tool.poe.tasks.ci]
cmd = "pytest -xsvm 'ci and not skip' --tb=long tests/"

[tool.pytest.ini_options]
markers = [
  "dev",
  "ci",
  "stage",
  "prod"
]

filterwarnings = [
  "ignore::DeprecationWarning"
]

