apiVersion: apps/v1
kind: Deployment
metadata:
  name: target
spec:
  selector:
    matchLabels:
      app: target
  template:
    metadata:
      labels:
        app: target
    spec:
      containers:
      - name: target
        image: target
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: target
