name: Tilt CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tilt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Tilt CI with snapshot
        run: |
          docker run --rm \
            -v $PWD:/app \
            -w /app \
            -v ${{ runner.temp }}:/out \
            tiltdev/tilt \
            tilt ci --output-snapshot-on-exit /out/tilt-snapshot.json

      - name: Upload snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: tilt-snapshot
          path: ${{ runner.temp }}/tilt-snapshot.json
