name: Tilt CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tilt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: helm/kind-action@v1
        with:
          version: v0.20.0

      - name: Install Tilt
        run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash

      - name: Run Tilt CI
        run: tilt ci --output-snapshot-on-exit tilt-snapshot.json

      - name: Upload snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: tilt-snapshot
          path: tilt-snapshot.json
