
name: Tilt CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tilt:
    runs-on: ubuntu-latest
    container:
      image: tiltdev/tilt
      options: --privileged  # Required for Kind to run Docker-in-Docker

    steps:
      - uses: actions/checkout@v4

      - name: Create Kind cluster with static API port
        run: |
          cat <<EOF > kind-config.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          networking:
            apiServerAddress: "0.0.0.0"
            apiServerPort: 6443
          EOF

          kind create cluster --config kind-config.yaml --name chart-testing

      - name: Patch kubeconfig for container access
        run: |
          sed -i "s|127.0.0.1:[0-9]*|host.docker.internal:6443|" /root/.kube/config

      - name: Run Tilt CI
        run: tilt ci --output-snapshot-on-exit tilt-snapshot.json

      - name: Upload snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: tilt-snapshot
          path: tilt-snapshot.json
