name: Tilt CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tilt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1
        with:
          version: v0.20.0

      - name: Run Tilt CI in container
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD":/work \
            -v "$HOME/.kube":/root/.kube \
            -w /work \
            tiltdev/tilt \
            tilt ci --namespace=target --output-snapshot-on-exit /work/tilt-snapshot.json

      - name: Upload snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: tilt-snapshot
          path: tilt-snapshot.json

