name: Tilt CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tilt:
    runs-on: ubuntu-latest
    container:
      image: tiltdev/tilt:latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Tilt CI with snapshot and apply trigger
        run: |
          kind create cluster --wait=1m
          kubectl wait --for=condition=ready node --all --timeout=60s
          kubectl cluster-info --context kind-kind
          #kubectl proxy &
          mkdir -p /out
          tilt ci --namespace target --output-snapshot-on-exit /out/tilt-snapshot.json

      - name: Upload snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: tilt-snapshot
          path: /out/tilt-snapshot.json
